version: '3.3'

volumes:
  collect_pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.14-alpine
    env_file: .env
    volumes:
      - collect_pg_data:/var/lib/postgresql/data
  
  backend:
    depends_on:
      - db
    image: smitona/collect_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media
    command: >
            bash -c "python manage.py collectstatic &&
                     cp -r /app/collected_static/. /backend_static/ &&
                     python manage.py migrate &&
                     python manage.py import_data &&
                     gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"

  nginx:
    depends_on:
      - backend
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media

  redis:
    depends_on:
      - backend
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
      - 6379
  
  celery:
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    build:
      context: ./backend
    env_file: .env
    command: celery -A backend worker -l info -P gevent


  